/**
 * @description       : 
 * @author            : Muriel Proton
 * @group             : 
 * @last modified on  : 23-06-2023
 * @last modified by  : Muriel Proton
**/
public with sharing class CRUDPermissionBeforSOQLDMLException extends Exception {
    //exception_createPermissionBeforeSQLDML(String typeOfSobject){
        //message of the exception 'You have no permission to insert an ' + typeOfSobject + ' record.'
    //}
}